# Generated by Django 5.2.4 on 2026-03-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ats_score',
            field=models.IntegerField(blank=True, help_text='ATS compatibility score (0-100)', null=True),
        ),
    ]
