# Generated by Django 5.2.4 on 2026-03-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_ats_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='domain',
            field=models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('fullstack', 'Full Stack Developer'), ('mobile', 'Mobile App Developer'), ('data_science', 'Data Scientist'), ('data_engineer', 'Data Engineer'), ('devops', 'DevOps Engineer'), ('qa', 'Quality Assurance'), ('product_manager', 'Product Manager'), ('marketing_manager', 'Marketing Manager'), ('hr', 'Human Resources'), ('sales', 'Sales Representative'), ('business_analyst', 'Business Analyst'), ('ui_ux', 'UI/UX Designer'), ('project_manager', 'Project Manager')], default='fullstack', help_text='The professional domain/field for this resume', max_length=20),
        ),
    ]
