# Generated by Django 5.2.4 on 2026-03-31 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='domain',
        ),
    ]
