# Generated by Django 5.2.4 on 2026-03-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='domain',
            field=models.CharField(blank=True, choices=[('software_engineering', 'Software Engineering'), ('data_science', 'Data Science'), ('product_management', 'Product Management'), ('design', 'Design'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('finance', 'Finance'), ('operations', 'Operations'), ('hr', 'Human Resources'), ('other', 'Other')], max_length=50),
        ),
    ]
