# Generated by Django 5.1 on 2026-08-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewsession_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='transcript_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='audio_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='interview_context',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='job_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='transcript_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='video_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
